### PR TITLE
CoW Swag page

### PR DESCRIPTION
**Pull request by fairlighteth**
Screenshot 2024-03-28 at 15 05 52

Screenshot 2024-03-28 at 15 05 19Screenshot 2024-03-28 at 15 05 27

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , great!
However, as usual, I have some issues to report. 
1. Desktop view: could you please add 'return' or 'order more' button in the end of the form? Or even share on Twitter button if someone wants to share this offer (2n option is too complicated)
return
2. Too many issues in a mobile interface: 
 - a line on opening
line
 - ugly scrollbar in Win
scrollbar
- buttons overlap text fields 
bottom
 - Once I received 1 validation message, then when I navigate to another form, it is already displayed on opening without filling in a field
on opening
 - when I want to change the value, it is not highlighted on click. I need to paste the cursor to it end, then press delete several times (not so easy to update it)
not easy to type
3. Some issues (from this [doc](https://docs.google.com/document/d/1rOfLfyK9AC3xhaqMd27bSnwadzM7TXWnOlk4vz0xXgM/edit)) are still not fixed (but they can be addressed in future PRs)

Thanks!

**Comment by fairlighteth** [comment]
Hi @elena-zh thanks for reviewing

1) Tried to see if there was a button option in Typeform. But right now I only see the option to add a Button which will be an external link. I propose to leave as is.

2) Most of the reported issues are inherent to Typeform, so we don't have direct control on that. 

Screenshot 2024-03-28 at 17 09 00


3) Addressed some items in there

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @fairlighteth , thanks for fixes!
Some issues that I still have: 
1. Sizes page for shorts is still not fixed. Fixed only for Jackets 
image
2. On some slides periods are missing. See images: 
image
periods

3. validation: I have ordered 4 jackets, but selected 5 sizes. Maybe remove 'multiselect' option here, WDYT? 
image
4. Might this be possible to remove this line in a mobile view? 
image

Thanks!

**Comment by fairlighteth** [comment]
1) Fixed.
2) Fixed.
3) For this version not changing this logic.
4) As it's part of the regular layout, opting for now changing that for now.

**Review by anxolin — APPROVED** [review]

**Pull request merged**
