### PR TITLE
Release v0.5.1

### PR DESCRIPTION
**Pull request by fairlighteth**
This release updates some layout issues and other reported issues.

## Changelog
20be521 fix selection text (#43)
741c5a8 Fix misc layout issues (#40)
1384e2e fix link color (#39)
00fa8b6 Update Safe logo (#38)

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , I have missed this issue while testing #40 
image
image

Could you please fix it?

**Comment by fairlighteth** [comment]
@elena-zh https://github.com/cowprotocol/cow-fi/pull/43

**Comment by fairlighteth** [comment]
Merged in #43 in this release branch

**Review by elena-zh — APPROVED** [review]
LGTM!

**Review by shoom3301 — APPROVED** [review]

**Pull request merged**
