### PR TITLE
fix: some PR issues

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes some issues mentioned by @elena-zh 

[Rename ](https://cowservices.slack.com/archives/C05D4B1P9CK/p1687426945376079)‘Tokens’ page (nicely) https://prnt.sc/teXXxeH-xwpR
Add ‘No tokens found’ when no search results
Copied’ alignment [does not look good](https://cowservices.slack.com/archives/C05D4B1P9CK/p1687446090680129) 
Allowed to type in a [negative ](https://cowservices.slack.com/archives/C05D4B1P9CK/p1687507284915659)amount

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @nenadV91 , thank you!
But I still can type in a negative amount 
image

Also, the app [does not look nice](https://www.loom.com/share/d3783f65ea5644a5a086c83a26cd2728) when it is loaded for the 1st time. Could you please check why?

**Review by anxolin — APPROVED** [review]

**Review by elena-zh — CHANGES_REQUESTED** [review]
The 4th case (negative amount in the field) is not fixed.

**Comment by nenadV91** [comment]
@elena-zh Fixed now

**Review by elena-zh — APPROVED** [review]
LGTM now!

**Pull request merged**
