### PR TITLE
Markup Category page and display all articles

### PR DESCRIPTION
**Pull request by anxolin**
This PR adds the markup for the categories pages. It also loads the articles for a category and present them

Before: Governance category
image

After: Governance category
image

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]
LGTM!

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @anxolin , coo. great!
Some nitpicks: 
1. I'd add a  hover effect on a category name (link color change)
image
2. Same for an article name under a category (+ add underline effect)
image
3. Great to have Back button, but for me it is displayed in a weird place (somewhere in the middle of the page). WDYT about displaying it at the top of the category? Or we can have 'back to top' button that will navigate to breadcrumbs at the top? 
image
image

4. The message is hardly visible for me 
image

Thanks!

**Comment by shoom3301** [comment]
Migrated the PR into monorepo https://github.com/cowprotocol/cowswap/pull/4334

**Comment by anxolin** [comment]
Merging and continuing with the comments in https://github.com/cowprotocol/cowswap/pull/4334

**Comment by anxolin** [comment]
@elena-zh I think those comments are a bit out of the scope. Think that I tried to styled as little as possible, because @fairlighteth is rebranding all, so changing this styles and layout will add code that won't be relevant anymore. 

Hold these comments for after the rebranding is done

**Pull request merged**
