### PR TITLE
Use constants for MetricsData

### PR DESCRIPTION
**Pull request by bh2smith**
Dune API V0 will be deprecated (in less than 2 weeks) and porting this to V1 will require substantial changes. Currently there is no NPM package to make this more straightforward so our best option is to revert to hardcoded values.

I have made a feature request to get a mapping of `{ query_id => execution_id }` from the API which would make this easier to integrate again in the future.

Please see [slack thread](https://cowservices.slack.com/archives/C036G0J90BU/p1663350875764059) for additional context.

Screenshot from preview linked below:
Screenshot 2022-09-19 at 7 49 22 PM

### CODE REVIEW

**Comment by anxolin** [comment]
But @bh2smith how can this be the solution? 

I think is not nice that they replace one for the other, but we cannot use it. 

Is there somewhere were i can read the migration to the v1. I think it would be sad to go back to static values.

**Comment by elena-zh** [comment]
Amounts do not match in Prod and in the preview link 
numbers

**Comment by bh2smith** [comment]
> Amounts do not match in Prod and in the preview link 
> 
> numbers
> 
> 

That's because this was yesterday.

**Comment by bh2smith** [comment]
> But @bh2smith how can this be the solution? 
> 
> 
> 
> I think is not nice that they replace one for the other, but we cannot use it. 
> 
> 
> 
> Is there somewhere were i can read the migration to the v1?. 
> 
> 
> 
> I think it would be sad to go back to static values.

I can tell you all about this, but it's a long story and (like I said) it is going to require a lot more engineering time. We can come back to it soon/later but I don't have the capacity for this at the moment. 

https://dune.com/docs/api/api-reference/authentication/

**Comment by bh2smith** [comment]
@anxolin and @alfetopito or anyone. We are continually being warned that this V0 endpoint is still in use. Can we get this out the door please.

**Comment by bh2smith** [comment]
Closing in favour of #35

**Pull request closed without merging**
