### PR TITLE
Add links footer

### PR DESCRIPTION
**Pull request by anxolin**
Updates the footer.

Before
image

After
image

### CODE REVIEW

**Comment by fairlighteth** [comment]
- One comment (cc @elena-zh ) is that on tablet the menu gets squeezed a bit. Something to optimize for later:
Screen Shot 2022-11-23 at 15 53 26

- Another point: The href url <a href="https://medium.com/@cow-protocol">Blog</a> needs a `_blank` target and also a `nofollow noopener`

**Comment by elena-zh** [comment]
Hey @anxolin , maybe we could rewrite it in this manner: 
  - remove CoW from the about section
  - add Protocol to the CoW
  - add CoW Swap to the FAQ
image

WDYT?

**Comment by elena-zh** [comment]
> Another point: The href url [Blog](https://medium.com/@cow-protocol) needs a _blank target and also a nofollow noopener

the same is for [Governance](https://snapshot.org/#/cow.eth) and [Forum](https://forum.cow.fi/)

**Comment by anxolin** [comment]
@elena-zh @fairlighteth i hope i addressed the issues above

**Review by elena-zh — APPROVED** [review]
Approved!

**Comment by fairlighteth** [comment]
All good, only thing is we miss the `rel` attribute with `nofollow noopener`

**Comment by anxolin** [comment]
Hei @fairlighteth, I will address this in another PR so I can just add some additional changes

**Comment by anxolin** [comment]
@fairlighteth I did this follow up PR (is overkill for adding just the `rel` but I couldn't help to do a small refactor) https://github.com/cowprotocol/cow-fi/pull/50

I read https://pointjupiter.com/what-noopener-noreferrer-nofollow-explained/ and my understanding is that `noopener` we want always, but `nofollow` not always. I did a proposal there for having 3 types of links. Maybe we can discuss in that PR.

**Pull request merged**
