### PR TITLE
Load stats from config + deprecate Dune v0

### PR DESCRIPTION
**Pull request by anxolin**
This PR replace the old deprecated API from Dune for a simple config file. 

This PR is an alternative to https://github.com/cowprotocol/cow-fi/pull/33 to make the stats more dynamic (so we can change without deploying). The idea is to buy time so we are not forced to use Dune v1 which is still undocumented and its not a priority for us.

## How does it work?
There's a new branch `configuration` where we will read from now on the stats. So we can change it from time to time without redeploying the website.

https://raw.githubusercontent.com/cowprotocol/cow-fi/configuration/config/stats.json

image

## Deprecation of Dune v0
The plan is to adapt dune, but not now (still waiting for the right time to do so). 

So this PR just stops using it, and for now we just deprecate it, so at least if you try to use it in the project you will see it strikedtrough:

image

## Test
- Verify the JSON and the website info matches. Keep in mind there's some rounding

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
LGTM!

**Review by nenadV91 — APPROVED** [review]
LGTM :+1:

**Review by bh2smith — APPROVED** [review]
This looks great (and better than what I had done in #33). Is there any special reason to add the deprecated flag instead of just removing all that dead code? I don't suspect it is being used elsewhere by anyone and won't be missed.

**Comment by anxolin** [comment]
> This looks great (and better than what I had done in https://github.com/cowprotocol/cow-fi/pull/33). Is there any special reason to add the deprecated flag instead of just removing all that dead code? I don't suspect it is being used elsewhere by anyone and won't be missed.

Good question. I don't like dead code flying around the project, but I just think I will reuse a bit of the v0 into the v1, so I prefer to adapt it. I think it will less work.

**Comment by bh2smith** [comment]
I really don't think we will ever use the anything similar for the v1 api (although it's nice to keep the methods around that get the values I suppose).

**Pull request merged**
